(function(){
  function icon(){return '<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 13h8"/><path d="M8 17h5"/></svg>'}
  function initials(name){return String(name||'IM').split(' ').filter(Boolean).map(function(w){return w[0]}).join('').slice(0,2).toUpperCase()}
  function certsFor(empId){var db=getDB();var days=(db.settings&&db.settings.expiration_alert_days)||30;return (db.certificates||[]).filter(function(c){return String(c.employee_id)===String(empId)&&c.status!=='cancelado'&&calcStatus(c.expiration_date,days)!=='vencido'})}
  function payload(emp,photo){return{full_name:emp.full_name,cpf:emp.cpf,rg:emp.rg,birth_date:emp.birth_date,phone:emp.phone,email:emp.email,address:emp.address,role_position:emp.role_position,department:emp.department,admission_date:emp.admission_date,status:emp.status,notes:emp.notes,photo_url:photo}}
  window.saveEmployeeCardPhoto=function(empId,input){var file=input.files&&input.files[0];if(!file)return;if(!file.type||file.type.indexOf('image/')!==0){showToast('Selecione uma imagem valida.','error');return}if(file.size>900000){showToast('Use uma foto menor que 900 KB para salvar no banco.','error');return}var emp=(getDB().employees||[]).find(function(e){return String(e.id)===String(empId)});if(!emp)return;var reader=new FileReader();reader.onload=async function(){try{await API.employees.update(empId,payload(emp,reader.result));await refreshData();await renderPage();showToast('Foto salva na carteirinha!','success')}catch(err){showToast('Erro ao salvar foto: '+err.message,'error')}};reader.readAsDataURL(file)}
  window.printEmployeeCard=function(empId){var card=document.getElementById('nr-card-'+empId);if(!card)return;var w=window.open('','_blank','width=900,height=700');w.document.write('<html><head><title>Carteirinha NR</title><link rel="stylesheet" href="/pro-dashboard.css"><link rel="stylesheet" href="/pro-polish.css"><link rel="stylesheet" href="/nr-idcards.css"></head><body><div class="print-area">'+card.outerHTML+'</div><script>setTimeout(function(){window.print();window.close()},300)</script></body></html>');w.document.close()}
  function renderQr(){if(typeof QRCode==='undefined')return;document.querySelectorAll('[data-nr-qr]').forEach(function(box){if(box.dataset.done)return;box.dataset.done='1';QRCode.toCanvas(box.dataset.nrQr,{width:74,margin:1},function(err,canvas){if(!err){box.innerHTML='';box.appendChild(canvas)}})})}
  function card(emp){var db=getDB();var settings=db.settings||{};var certs=certsFor(emp.id);var latest=certs.slice().sort(function(a,b){return new Date(a.expiration_date)-new Date(b.expiration_date)})[0];var qr=latest&&latest.verification_token?(location.origin+location.pathname+'#/verificar/'+latest.verification_token):location.href;var tags=certs.slice(0,8).map(function(c){return '<span>'+(c.training_code||'NR')+'</span>'}).join('')||'<span>Sem NR valida</span>';var photo=emp.photo_url?'<img class="nr-photo" src="'+emp.photo_url+'" alt="Foto de '+emp.full_name+'">':'<div class="nr-photo-empty">'+initials(emp.full_name)+'</div>';return '<div class="nr-id-wrap"><article class="nr-id-card" id="nr-card-'+emp.id+'"><div class="nr-card-top"><div><p class="text-xs text-blue-100/80 font-bold uppercase tracking-wide">'+(settings.company_name||'IMEC Compliance')+'</p><h3 class="font-display text-lg font-extrabold">Carteira de Qualificacao NR</h3></div><div class="text-right"><p class="text-[10px] uppercase text-blue-100/80">Status</p><p class="font-bold">'+(certs.length?'APTO':'PENDENTE')+'</p></div></div><div class="nr-card-body"><div class="nr-card-info">'+photo+'<div><h4 class="nr-card-name">'+emp.full_name+'</h4><div class="nr-field"><span>Funcao</span><strong>'+(emp.role_position||'-')+'</strong></div><div class="nr-field"><span>Setor</span><strong>'+(emp.department||'-')+'</strong></div></div></div><div class="grid grid-cols-2 gap-3 mt-3"><div class="nr-field"><span>CPF</span><strong>'+formatCPF(emp.cpf||'')+'</strong></div><div class="nr-field"><span>RG</span><strong>'+(emp.rg||'-')+'</strong></div><div class="nr-field"><span>Admissao</span><strong>'+formatDate(emp.admission_date)+'</strong></div><div class="nr-field"><span>Menor validade</span><strong>'+(latest?formatDate(latest.expiration_date):'-')+'</strong></div></div><div class="nr-field"><span>Treinamentos NR validos</span><div class="nr-list">'+tags+'</div></div><div class="nr-card-footer"><p class="text-[10px] leading-tight text-slate-500 max-w-[260px]">Documento auxiliar de identificacao e controle. A comprovacao normativa deve ser feita pelo certificado/registro completo do treinamento.</p><div class="nr-qr" data-nr-qr="'+qr+'"></div></div></div></article><div class="nr-actions"><label class="btn btn-outline btn-sm"><input class="nr-photo-input" type="file" accept="image/*" onchange="saveEmployeeCardPhoto(\''+emp.id+'\',this)">Adicionar foto</label><button class="btn btn-primary btn-sm" onclick="printEmployeeCard(\''+emp.id+'\')">Imprimir / PDF</button></div></div>'}
  function install(){if(typeof renderers==='undefined')return false;renderers.idcards=async function(){var emps=(getDB().employees||[]).filter(function(e){return e.status==='ativo'});var body=emps.length?emps.map(card).join(''):'<div class="pro-empty">'+icon()+'<div><strong>Nenhum funcionario ativo</strong><p class="mt-1 text-sm">Cadastre um funcionario ativo para gerar a carteirinha.</p></div></div>';setTimeout(renderQr,80);return '<div class="nr-card-toolbar"><div><h3 class="font-display text-xl font-extrabold text-slate-900">Carteirinhas NR com foto</h3><p class="text-sm text-slate-500">Gere carteirinhas auxiliares de identificacao, com foto, QR Code e NRs validas do colaborador.</p></div><button class="btn btn-outline btn-sm" onclick="window.print()">Imprimir todas</button></div><div class="nr-card-grid print-area">'+body+'</div>'};return true}
  function boot(){if(!install())setTimeout(boot,80)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot()
})();
